services:
  catalogue:
    image: catalogue:v1 
    container_name: catalogue 
    depends_on: 
    - mongodb
  mongodb:
    image: mongodb:v1
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis
      

networks:
  default:
    driver: bridge
    name: roboshop
    external: false #true if you have created network manually by using docker command
